language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - raquelserranor@hotmail.com
script:
#Test unitario y de integracion en develop
- mvn verify --settings settings.xml
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent verify --settings settings.xml
- mvn sonar:sonar -Dsonar.organization=raquelsr-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=61cf32b8ff7a3e271a2099fbac28be6789110311 --settings settings.xml